### ISSUE TITLE
Warning when trying to validate against extended Record

### ISSUE THREAD

**Issue by jjeising** [HurricaneJames/react-immutable-proptypes#33]
I'm trying to validate a map of Records. The Record is extended:
```js
class Bar extends Immutable.Record({
  example: null
}) {
  constructor(data) {
    // …
    super(data);
  }
}

// Later:
static propTypes = {
   foo: ImmutablePropTypes.mapOf(Bar).isRequired
};
```
This issues a warning in checkPropTypes:
```
Warning: Failed propType: Cannot call a class as a function Check the render method of `...`
```
Validating against a map of a plain Record works fine.

**Comment by Lexicality** [comment]
The problem is that `Bar` isn't a prop type validator function, it's a class.
Try `ImmutablePropTypes.mapOf(React.PropTypes.instanceOf(Bar)).isRequired` instead?

As a side note, passing the result of a record 'works' because Immutable objects behave really weirdly regarding instantiation and prop type validators are considered to have passed if they do not return an `Error` object. Effectively you are passing `React.PropTypes.any`, which is probably not what you wanted!

**Comment by jjeising** [comment]
Ah, this works fine and errors as expected when supplied with the wrong record. Just got the documentation wrong – in retrospect it seems clear as the examples show nesting which otherwise probably wouldn't work.
