### ISSUE TITLE
Note that invalid prop is an Immutable data structure if it is

### ISSUE THREAD

**Issue by garetht** [HurricaneJames/react-immutable-proptypes#7]
If an `ImmutablePropType`, say `Immutable.listOf(React.PropTypes.string)` is specified, but an `Immutable.Map` is provided instead, the warning message says `Warning: Failed propType: Invalid prop...of type object supplied`. Since this is an Immutable-specific library, it might be helpful to say that the type of the prop provided was an `Immutable.Map`, although I suppose it might not be straightforward.

**Comment by HurricaneJames** [comment]
There are two ways to read this. First, that an `Immutable.Map` is provided instead of a string. It would be near impossible to fix that warning message because the type checker that fails is `React.PropTypes.string`. React has no knowledge of Immutable.js.

The other way to read your issue is that `listOf` is specified, but a `Map` is passed instead of a `List`. If that is what you mean, then I can do something about that. Check out v 1.5.0. It should provide more meaningful error messages.

**Comment by garetht** [comment]
Thanks! I think I meant the second - sorry for the lack of clarity.
